// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCRIpYJqyEzn3inVe4QtxlKcp7NU92_1tg',
    appId: '1:106123708646:web:6e3fa160f3fd1d046e1327',
    messagingSenderId: '106123708646',
    projectId: 'teste-leo-calculadora',
    authDomain: 'teste-leo-calculadora.firebaseapp.com',
    databaseURL: 'https://teste-leo-calculadora-default-rtdb.firebaseio.com',
    storageBucket: 'teste-leo-calculadora.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDHf05tUJCizkfL3iQMaFDtXA8JXvQT0L4',
    appId: '1:106123708646:android:0884f73781ff43006e1327',
    messagingSenderId: '106123708646',
    projectId: 'teste-leo-calculadora',
    databaseURL: 'https://teste-leo-calculadora-default-rtdb.firebaseio.com',
    storageBucket: 'teste-leo-calculadora.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyA2Tob2u-syPZanuZPRAiiIh-10LA1M3zA',
    appId: '1:106123708646:ios:992a71717b94f0516e1327',
    messagingSenderId: '106123708646',
    projectId: 'teste-leo-calculadora',
    databaseURL: 'https://teste-leo-calculadora-default-rtdb.firebaseio.com',
    storageBucket: 'teste-leo-calculadora.appspot.com',
    iosClientId: '106123708646-dncn5eq18up4uat96e7n5ggg0hdrns7g.apps.googleusercontent.com',
    iosBundleId: 'com.example.testeLogin',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyA2Tob2u-syPZanuZPRAiiIh-10LA1M3zA',
    appId: '1:106123708646:ios:992a71717b94f0516e1327',
    messagingSenderId: '106123708646',
    projectId: 'teste-leo-calculadora',
    databaseURL: 'https://teste-leo-calculadora-default-rtdb.firebaseio.com',
    storageBucket: 'teste-leo-calculadora.appspot.com',
    iosClientId: '106123708646-dncn5eq18up4uat96e7n5ggg0hdrns7g.apps.googleusercontent.com',
    iosBundleId: 'com.example.testeLogin',
  );
}
